/* eslint-disable @next/next/no-img-element -- Reference PNG crops require exact native image sizing. */
"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { classTimes, days, requests, reviews, studios } from "@/lib/flowly-data";
import { useFlowly } from "./app-state";
import { FlowlyIcon, type FlowlyIconName } from "./icons";
import { BottomNav, Brand, DatePicker, Field, InstructorRow, PrimaryButton, SettingRow, StatusBadge, StudioRow, TopBar } from "./ui";

export type FlowlyScreenId = "splash" | "onboarding" | "signup" | "login" | "reset" | "location" | "discover" | "map" | "search" | "studio" | "instructor" | "class-select" | "booking-summary" | "success" | "bookings" | "booking-detail" | "favorites" | "reviews" | "write-review" | "profile" | "settings" | "notifications" | "trainer-dashboard" | "new-class" | "requests" | "request-detail" | "trainer-calendar";

function ScreenShell({ children, className = "", nav, trainer = false }: { children: React.ReactNode; className?: string; nav?: boolean; trainer?: boolean }) {
  return <main className={`flowly-app ${className}`}><div className="flowly-phone">{children}{nav && <BottomNav trainer={trainer}/>}</div></main>;
}

function AuthForm({ mode }: { mode: "signup" | "login" | "reset" }) {
  const router = useRouter();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [password, setPassword] = useState("");
  const [accepted, setAccepted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const errors = {
    name: submitted && mode === "signup" && name.trim().length < 2 ? "Ad soyad gerekli" : "",
    email: submitted && !/^\S+@\S+\.\S+$/.test(email) ? "Geçerli bir e-posta gir" : "",
    phone: submitted && mode === "signup" && phone.replace(/\D/g, "").length < 10 ? "Telefon numarası eksik" : "",
    password: submitted && mode !== "reset" && password.length < 6 ? "Şifre en az 6 karakter olmalı" : "",
  };
  const invalid = Boolean(
    (mode === "signup" && name.trim().length < 2) ||
    !/^\S+@\S+\.\S+$/.test(email) ||
    (mode === "signup" && phone.replace(/\D/g, "").length < 10) ||
    (mode !== "reset" && password.length < 6) ||
    (mode === "signup" && !accepted)
  );
  function submit(event: FormEvent) {
    event.preventDefault(); setSubmitted(true);
    if (invalid || !email) return;
    setLoading(true);
    window.setTimeout(() => router.push(mode === "reset" ? "/giris?reset=sent" : "/konum-izni"), 550);
  }
  return <form onSubmit={submit} className="auth-form-v4">
    {mode === "signup" && <Field label="Ad Soyad" icon="user" value={name} onChange={setName} error={errors.name}/>}
    <Field label="E-posta" icon="mail" type="email" value={email} onChange={setEmail} placeholder={mode === "reset" ? "ornek@mail.com" : "ornek@eposta.com"} error={errors.email}/>
    {mode === "signup" && <Field label="Telefon" icon="phone" type="tel" value={phone} onChange={setPhone} error={errors.phone}/>}
    {mode !== "reset" && <Field label="Şifre" icon="lock" type="password" value={password} onChange={setPassword} placeholder="Şifreni gir" error={errors.password}/>}
    {mode === "login" && <Link href="/sifre-sifirlama" className="auth-forgot">Şifremi unuttum</Link>}
    {mode === "signup" && <label className={`check-row${submitted && !accepted ? " has-error" : ""}`}><input type="checkbox" checked={accepted} onChange={(event) => setAccepted(event.target.checked)}/><span><u>Kullanım Koşulları</u> ve <u>Gizlilik Politikasını</u> okudum, kabul ediyorum.</span></label>}
    <PrimaryButton loading={loading}>{mode === "signup" ? "Üye Ol" : mode === "login" ? "Giriş Yap" : "Bağlantı Gönder"}</PrimaryButton>
  </form>;
}

function SplashScreen() { return <ScreenShell className="splash-screen"><Link href="/onboarding" className="splash-link" aria-label="Flowly'ye başla"><div className="splash-photo"/><div className="splash-logo"><Brand light/><p>PILATES.<br/>NEARBY.<br/>ON YOUR TERMS.</p></div></Link></ScreenShell>; }
function OnboardingScreen() { return <ScreenShell className="onboarding-screen"><div className="onboarding-photo"/><div className="onboarding-brand"><Brand light/><div className="progress-lines"><i/><i/><i/></div></div><div className="onboarding-copy"><h1>Bedeninle tekrar<br/>bağlantı kur.</h1><p>Sana yakın stüdyoları keşfet,<br/>kendi ritminde hareket et.</p><PrimaryButton href="/uye-ol" outline>Başla</PrimaryButton><Link href="/giris">Giriş Yap</Link></div></ScreenShell>; }

function SignupScreen() { return <ScreenShell className="auth-screen signup-screen"><TopBar back action={<Brand/>}/><section><h1>Aramıza<br/>katıl.</h1><p>Pilatesin dönüştürücü etkisini<br/>birlikte yaşayalım.</p><AuthForm mode="signup"/><div className="auth-switch"><span>Zaten hesabın var mı?</span><Link href="/giris">Giriş Yap</Link></div></section><div className="auth-photo studio"/></ScreenShell>; }
function LoginScreen() { return <ScreenShell className="auth-screen login-screen"><div className="login-flower"/><TopBar back/><Brand/><section><h1>Tekrar<br/>hoş geldin.</h1><AuthForm mode="login"/><div className="auth-divider"><span>veya</span></div><button className="social-button"><span>●</span> Apple ile devam et</button><button className="social-button"><span className="google-mark">G</span> Google ile devam et</button><div className="auth-switch"><span>Hesabın yok mu?</span><Link href="/uye-ol">Üye Ol</Link></div></section></ScreenShell>; }
function ResetScreen() { return <ScreenShell className="auth-screen reset-screen"><TopBar/><section><Brand/><h1>Şifreni<br/>yenile.</h1><p>E-posta adresine bir yenileme<br/>bağlantısı göndereceğiz.</p><AuthForm mode="reset"/><Link href="/giris" className="center-link">Girişe dön</Link></section><div className="iris-photo"/></ScreenShell>; }
function LocationScreen() { const router = useRouter(); return <ScreenShell className="location-screen"><section><Brand/><p className="brand-tagline">PILATES.<br/>NEARBY.<br/>ON YOUR TERMS.</p><h1>Yakınındaki<br/>akışı bul.</h1><div className="location-flower"><div className="pin-outline"><FlowlyIcon name="pin" size={160}/></div></div><p className="location-copy">Sana en yakın stüdyoları ve uygun<br/>dersleri gösterebilmemiz için<br/>konumuna ihtiyacımız var.</p><PrimaryButton onClick={() => router.push("/kesfet")}>Konumumu Kullan</PrimaryButton><button className="text-button" onClick={() => router.push("/kesfet")}>Şimdilik geç</button><div className="privacy-note"><FlowlyIcon name="lock"/><p>Konum bilgilerin sadece sana en yakın stüdyoları göstermek için kullanılır.</p></div></section></ScreenShell>; }

function DiscoverScreen() {
  return <ScreenShell className="feed-screen" nav><div className="status-row"><span>9:41</span><span>▮▮▮ ◉ ▰</span></div><header className="feed-header"><div><Brand/><Link href="/harita" className="location-link"><FlowlyIcon name="pin"/>İstanbul / Kadıköy⌄</Link></div><Link href="/arama" aria-label="Ara"><FlowlyIcon name="search" size={31}/></Link></header><section className="page-content"><h1>Yakınındaki<br/>dersleri keşfet.</h1><div className="tab-row"><button className="is-active">Reformer</button><button>Mat</button><button>Klinik Pilates</button><button>Tümü</button></div><div className="studio-list">{studios.map((studio) => <StudioRow key={studio.id} studio={studio}/>)}</div></section></ScreenShell>;
}

function MapScreen() { return <ScreenShell className="map-screen" nav><TopBar title="Yakındaki Stüdyolar" action={<div className="top-actions"><Link href="/arama"><FlowlyIcon name="search"/></Link><Link href="/arama"><FlowlyIcon name="filter"/></Link></div>}/><div className="map-visual"/><section className="map-results"><div className="section-title-row"><h2>Bu bölgede 12 stüdyo</h2><span>Mesafeye göre⌄</span></div>{studios.slice(0,2).map((studio) => <StudioRow key={studio.id} studio={studio}/>)}</section></ScreenShell>; }

function SearchScreen() {
  const router = useRouter(); const [query, setQuery] = useState(""); const [types, setTypes] = useState<string[]>([]); const [date, setDate] = useState("6"); const [distance, setDistance] = useState("5");
  const lessons = [{ name: "Reformer", image: studios[0].image }, { name: "Mat", image: "/images/flowly/mat.webp" }, { name: "Klinik Pilates", image: studios[1].image }, { name: "Cadillac", image: studios[0].image }];
  function toggleType(type: string) { setTypes((current) => current.includes(type) ? current.filter((item) => item !== type) : [...current, type]); }
  return <ScreenShell className="search-screen" nav><TopBar/><section><h1>Aradığın<br/>dersi bul.</h1><label className="search-box"><FlowlyIcon name="search"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Stüdyo, eğitmen veya semt ara"/></label><div className="filter-group"><h2>Ders türü</h2>{lessons.map((lesson) => <label className="lesson-filter" key={lesson.name}><input type="checkbox" checked={types.includes(lesson.name)} onChange={() => toggleType(lesson.name)}/><img src={lesson.image} alt=""/><span>{lesson.name}</span></label>)}</div><div className="filter-group"><h2>Zaman</h2><div className="search-dates">{["4","5","6","7","8","9","10"].map((item, index) => <button key={item} className={date === item ? "is-selected" : ""} onClick={() => setDate(item)}><span>{["Bugün","Yarın","Pzt","Sal","Çar","Per","Cum"][index]}</span><strong>{item}</strong><small>Eki</small></button>)}</div></div><div className="filter-group range-group"><h2>Mesafe</h2><div><span>0 km</span><strong>{distance} km</strong><span>20 km</span></div><input type="range" min="0" max="20" value={distance} onChange={(event) => setDistance(event.target.value)}/></div><div className="filter-group"><h2>Fiyat aralığı</h2><div className="price-row"><input placeholder="Min. fiyat"/><input placeholder="Maks. fiyat"/></div></div><PrimaryButton onClick={() => router.push(`/kesfet?q=${encodeURIComponent(query)}&types=${types.join(",")}`)}>18 sonucu göster</PrimaryButton><button className="text-button" onClick={() => { setQuery(""); setTypes([]); setDistance("5"); }}>Temizle</button></section></ScreenShell>;
}

function StudioScreen() {
  const flowly = useFlowly(); const router = useRouter(); const favorite = flowly.favorites.includes("move"); const [day, setDay] = useState("4");
  return <ScreenShell className="studio-screen"><div className="studio-hero"><TopBar action={<div className="top-actions"><button onClick={() => flowly.toggleFavorite("move")} className={favorite ? "is-favorite" : ""}><FlowlyIcon name="heart"/></button><button><FlowlyIcon name="share"/></button></div>}/><span>1/5</span></div><section><div className="studio-title"><h1>Move Studio</h1><span className="rating">★ <b>4.9</b> (120)</span></div><p className="location-link"><FlowlyIcon name="pin"/>Kadıköy · 0.8 km</p><div className="tag-row"><span>Reformer</span><span>Mat</span><span>Küçük Grup</span></div><p className="studio-description">Modern ve ferah stüdyomuzda, alanında uzman eğitmenlerle bedenini güçlendiren, zihnini dengeleyen dersler seni bekliyor.</p><div className="tab-row"><button className="is-active">Dersler</button><Link href="/egitmen/duygu-kaya">Eğitmenler</Link><Link href="/yorumlar">Yorumlar</Link><button>Hakkında</button></div><div className="compact-dates">{days.map((item) => <button key={item.date} className={day === item.date ? "is-selected" : ""} onClick={() => setDay(item.date)}><span>{item.day}</span><strong>{item.date} {item.month}</strong></button>)}</div><div className="class-list">{classTimes.map((item) => <button key={item.time} onClick={() => { if (item.status !== "Dolu") { flowly.setSelectedTime(item.time); router.push("/rezervasyon/ders-sec"); } }}><div><strong>{item.time}</strong><span>{item.duration}</span></div><div><strong>{item.title}</strong><span>{item.teacher}</span></div>{item.status && <StatusBadge tone={item.tone === "blue" ? "blue" : "plum"}>{item.status}</StatusBadge>}</button>)}</div><PrimaryButton href="/rezervasyon/ders-sec">Rezervasyon Yap</PrimaryButton></section></ScreenShell>;
}

function InstructorScreen() { return <ScreenShell className="instructor-screen"><TopBar title="Eğitmen"/><div className="instructor-hero"/><section><h1>Duygu Kaya</h1><p className="subtitle">Pilates Eğitmeni</p><div className="instructor-meta"><span className="rating">★ 4.9 (120)</span><span><FlowlyIcon name="pin"/>Kadıköy</span></div><blockquote>“Hareket, bedenle kurduğun<br/>en dürüst bağdır.”</blockquote><div className="about-row"><strong>Hakkında</strong><p>Bedenin doğal ritmini önemseyen, kişiye özel ve bütünsel bir yaklaşım benimseyen Duygu, hareketin hayatın her döneminde iyileştirici gücüne inanır.</p></div><h2>Uzmanlıklar</h2><div className="expertise"><span><FlowlyIcon name="mat"/>Reformer Pilates</span><span><FlowlyIcon name="document"/>Klinik Pilates</span><span><FlowlyIcon name="user"/>Hamile Pilates</span></div><div className="section-title-row"><h2>Yaklaşan Dersler</h2><span>Tümünü Gör →</span></div><div className="mini-class-list">{["Reformer Pilates","Mat Pilates","Klinik Pilates"].map((item,index) => <Link href="/rezervasyon/ders-sec" key={item}><img src={studios[index].image} alt=""/><div><strong>{item}</strong><span>{4+index} Ekim · {index === 0 ? "18:30" : "10:00"}</span><span>{studios[index].name} · Kadıköy</span></div><b>{2+index} / 8<br/><small>Kişi</small></b><FlowlyIcon name="arrow-right"/></Link>)}</div><PrimaryButton href="/rezervasyon/ders-sec">Derslerini Gör</PrimaryButton></section></ScreenShell>; }

function ClassSelectScreen() { const flowly = useFlowly(); return <ScreenShell className="class-select-screen"><TopBar title="Ders ve saat seç"/><section><Link href="/studyo/move-studio" className="selected-studio"><img src={studios[0].image} alt=""/><div><strong>Move Studio</strong><span>Reformer Pilates</span><span><FlowlyIcon name="pin"/>Kadıköy · 0.8 km</span></div><FlowlyIcon name="arrow-right"/></Link><div className="month-row"><h1>Ekim 2026</h1><span>‹　›</span></div><DatePicker value={flowly.selectedDay} onChange={flowly.setSelectedDay}/><h1>Ders türü</h1><div className="tab-row"><button className="is-active">Reformer</button><button>Mat</button><button>Klinik</button></div><div className="selectable-times">{classTimes.map((item) => <button key={item.time} disabled={item.status === "Dolu"} className={flowly.selectedTime === item.time ? "is-selected" : ""} onClick={() => flowly.setSelectedTime(item.time)}><div><strong>{item.time}</strong><span>{item.duration}</span></div><div><strong>{item.title}</strong><span>{item.teacher}</span></div>{item.status === "Dolu" ? <StatusBadge tone="plum">Dolu</StatusBadge> : item.status ? <StatusBadge tone="blue">{item.status}</StatusBadge> : <i><FlowlyIcon name="check"/></i>}</button>)}</div><div className="selection-summary">{flowly.selectedDay} Ekim · {flowly.selectedTime} · 450 TL</div><PrimaryButton href="/rezervasyon/ozet">Devam Et</PrimaryButton></section></ScreenShell>; }

function BookingSummaryScreen() { const router = useRouter(); const flowly = useFlowly(); const [loading, setLoading] = useState(false); function confirm() { setLoading(true); window.setTimeout(() => { flowly.setBookingCreated(true); flowly.setBookingStatus("pending"); router.push("/rezervasyon/basarili"); }, 500); } return <ScreenShell className="summary-screen"><TopBar title="Rezervasyon"/><section><div className="booking-overview"><img src={studios[0].image} alt=""/><div><h2>Move Studio</h2><p>Reformer Pilates</p><p>4 Ekim Cumartesi</p><p>18:30 · 50 dk</p></div></div><div className="summary-rows"><InstructorRow compact/><SummaryRow icon="level" label="Seviye" value="Orta Seviye"/><SummaryRow icon="users" label="Kontenjan" value="2 kişilik yer kaldı"/><SummaryRow icon="pin" label="Stüdyo" value="Kadıköy · 0.8 km"/><SummaryRow icon="document" label="İptal Politikası" value="Derse 12 saat kalana kadar ücretsiz iptal edilebilir."/></div><PrimaryButton loading={loading} onClick={confirm}>Rezervasyon Talebi Gönder</PrimaryButton></section></ScreenShell>; }

function SummaryRow({ icon, label, value }: { icon: FlowlyIconName; label: string; value: string }) { return <div className="summary-row"><span>{label}</span><FlowlyIcon name={icon}/><p>{value}</p><FlowlyIcon name="arrow-right" size={19}/></div>; }

function SuccessScreen() { return <ScreenShell className="success-screen"><div className="success-photo"/><section><div className="success-check"><FlowlyIcon name="check" size={40}/></div><h1>Talebin alındı.</h1><p>Eğitmen onayladığında rezervasyonun<br/>kesinleşecek ve sana bildireceğiz.</p><div className="success-details"><SummaryLine icon="calendar" label="TARİH" value="4 Ekim Cumartesi"/><SummaryLine icon="clock" label="SAAT" value="18:30 – 50 dk"/><SummaryLine icon="pin" label="STÜDYO" value="Move Studio"/></div><PrimaryButton href="/rezervasyonlar/move-studio-4-ekim" outline>Talebi Gör</PrimaryButton><Link href="/kesfet">Keşfe Dön</Link><Brand light/></section></ScreenShell>; }
function SummaryLine({ icon, label, value }: { icon: FlowlyIconName; label: string; value: string }) { return <div><FlowlyIcon name={icon}/><p><span>{label}</span><strong>{value}</strong></p></div>; }

function BookingsScreen() { const flowly = useFlowly(); const pending = flowly.bookingCreated && flowly.bookingStatus === "pending"; return <ScreenShell className="bookings-screen" nav><div className="status-row"><span>9:41</span><span>▮▮▮ ◉ ▰</span></div><section><Brand/><h1>Rezervasyonlarım</h1><div className="tab-row small"><button className="is-active">Yaklaşan</button><button>Geçmiş</button></div><div className="featured-booking"><img src={studios[0].image} alt=""/><div className="booking-info"><div className="date-block"><strong>04</strong><span>EKİ</span></div><div><h2>Move Studio</h2><p>Reformer Pilates</p><p>{flowly.selectedTime} · 50 dk</p><InstructorRow compact/></div><StatusBadge tone={pending ? "blue" : "moss"}>● {pending ? "Onay bekliyor" : "Onaylandı"}</StatusBadge></div><div className="booking-actions"><PrimaryButton href="/rezervasyonlar/move-studio-4-ekim">Detayı Gör</PrimaryButton><PrimaryButton outline>Yol Tarifi</PrimaryButton></div></div><div className="booking-list-row"><div className="date-block"><strong>09</strong><span>EKİ</span></div><div><h2>Studio 11</h2><p>Mat Pilates</p><p>10:00 · 45 dk</p></div><StatusBadge tone="moss">● Onaylandı</StatusBadge><FlowlyIcon name="arrow-right"/></div>{pending && <p className="local-state-note">Talebin eğitmen onayını bekliyor.</p>}</section></ScreenShell>; }

function BookingDetailScreen() { const router = useRouter(); const flowly = useFlowly(); const [cancelled, setCancelled] = useState(flowly.bookingStatus === "cancelled"); const pending = flowly.bookingCreated && flowly.bookingStatus === "pending"; function cancel() { setCancelled(true); flowly.setBookingStatus("cancelled"); } return <ScreenShell className="booking-detail-screen"><TopBar title="Rezervasyon Detayı"/><section><img className="detail-studio-image" src={studios[0].image} alt="Move Studio"/><div className="detail-heading"><h1>Move Studio</h1><StatusBadge tone={cancelled ? "plum" : pending ? "blue" : "moss"}>● {cancelled ? "İptal edildi" : pending ? "Onay bekliyor" : "Onaylandı"}</StatusBadge></div><div className="detail-list"><SummaryRow icon="calendar" label="Tarih" value="4 Ekim Cumartesi"/><SummaryRow icon="clock" label="Saat" value={`${flowly.selectedTime} · 50 dk`}/><SummaryRow icon="level" label="Ders" value="Reformer Pilates"/><SummaryRow icon="user" label="Eğitmen" value="Duygu K."/><SummaryRow icon="pin" label="Stüdyo" value="Kadıköy — Caferağa Mah. Moda Cad. No:12"/></div><div className="detail-map"/><div className="policy-row"><FlowlyIcon name="document"/><p><strong>İptal Politikası</strong><span>Derse 12 saat kalana kadar ücretsiz iptal edebilirsin.</span></p></div><PrimaryButton href="/rezervasyon/ders-sec" outline>Ders Saatini Değiştir</PrimaryButton><PrimaryButton>Yol Tarifi Al</PrimaryButton><button className="danger-link" disabled={cancelled} onClick={cancel}>{cancelled ? "Rezervasyon iptal edildi" : "Rezervasyonu İptal Et"}</button>{cancelled && <button className="text-button" onClick={() => router.push("/rezervasyonlar")}>Rezervasyonlara dön</button>}</section></ScreenShell>; }

function FavoritesScreen() { const flowly = useFlowly(); const favoriteStudios = studios.filter((studio) => flowly.favorites.includes(studio.id)); return <ScreenShell className="favorites-screen" nav><header className="brand-action"><Brand/><Link href="/arama"><FlowlyIcon name="search"/></Link></header><section><h1>Favorilerin</h1><div className="tab-row small"><button className="is-active">Stüdyolar</button><button>Eğitmenler</button></div>{favoriteStudios.length ? favoriteStudios.map((studio,index) => <div key={studio.id}><StudioRow studio={studio} favorite onFavorite={() => flowly.toggleFavorite(studio.id)}/>{index === 0 && <p className="favorite-note"><span/>Dönmek istediğin yerler, burada.<span/></p>}</div>) : <div className="empty-state"><FlowlyIcon name="heart" size={46}/><h2>Henüz favorin yok.</h2><Link href="/kesfet">Stüdyoları keşfet</Link></div>}</section></ScreenShell>; }

function ReviewsScreen() { return <ScreenShell className="reviews-screen"><TopBar title="Yorumlar"/><section><div className="rating-summary"><div><strong>4.9</strong><p>★★★★★</p><span>120 değerlendirme</span></div><div className="rating-bars">{[[5,98],[4,16],[3,4],[2,2],[1,0]].map(([star,count]) => <div key={star}><span>{star} ★</span><i><b style={{width: `${count}%`}}/></i><em>{count}</em></div>)}</div></div><div className="tab-row small"><button className="is-active">Tümü</button><button>En Yeni</button><button>En Yüksek</button></div><div className="review-list">{reviews.map((review,index) => <article key={review.name}><img src={index % 2 ? "/images/flowly/member-selin.webp" : "/images/flowly/onboarding.webp"} alt=""/><div><div><strong>{review.name}</strong><time>{review.date}</time></div><span>{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</span><p>{review.text}</p></div></article>)}</div><PrimaryButton href="/yorum-yaz" outline>Yorum Yaz</PrimaryButton></section></ScreenShell>; }

function WriteReviewScreen() { const router = useRouter(); const [rating, setRating] = useState(4); const [comment, setComment] = useState(""); const [teacher, setTeacher] = useState(false); const [studio, setStudio] = useState(false); const [loading, setLoading] = useState(false); function submit(event: FormEvent) { event.preventDefault(); if (!comment.trim()) return; setLoading(true); window.setTimeout(() => router.push("/yorumlar?sent=1"), 500); } return <ScreenShell className="write-review-screen"><TopBar title="Deneyimini paylaş"/><section><div className="booking-overview"><img src={studios[0].image} alt=""/><div><h2>Move Studio</h2><p>Reformer Pilates</p><p><FlowlyIcon name="calendar"/>4 Ekim Cumartesi<br/>18:30 - 50 dk</p></div></div><h1>Dersin nasıldı?</h1><div className="star-picker">{[1,2,3,4,5].map((star) => <button key={star} onClick={() => setRating(star)} aria-label={`${star} yıldız`}>{star <= rating ? "★" : "☆"}</button>)}</div><form onSubmit={submit}><label className="review-input"><span>Yorumun</span><textarea value={comment} onChange={(event) => setComment(event.target.value)} maxLength={500} placeholder="Deneyimini birkaç cümleyle anlat..."/><small>{comment.length}/500</small></label><label className="check-row"><input type="checkbox" checked={teacher} onChange={(event) => setTeacher(event.target.checked)}/>Eğitmeni öneririm</label><label className="check-row"><input type="checkbox" checked={studio} onChange={(event) => setStudio(event.target.checked)}/>Stüdyoyu öneririm</label><PrimaryButton loading={loading} disabled={!comment.trim()}>Yorumu Yayınla</PrimaryButton></form></section></ScreenShell>; }

function ProfileScreen() { return <ScreenShell className="profile-screen" nav><header className="brand-action"><Brand/><Link href="/profil/ayarlar"><FlowlyIcon name="settings" size={30}/></Link></header><section><div className="profile-hero"><img src="/images/flowly/onboarding.webp" alt="Elif Yılmaz"/><div><h1>Elif Yılmaz</h1><p><FlowlyIcon name="pin"/>Kadıköy, İstanbul</p><Link href="/profil/ayarlar">Profili Düzenle</Link></div></div><h2>Akışın, senin ritmin.</h2><div className="profile-stats"><div><strong>12</strong><span>Ders</span></div><div><strong>4</strong><span>Favori</span></div><div><strong>6</strong><span>Yorum</span></div></div><div className="settings-list"><SettingRow icon="user" label="Üyelik ve Paketler"/><SettingRow icon="card" label="Ödeme Yöntemleri"/><SettingRow icon="bell" label="Bildirimler" href="/bildirimler"/><SettingRow icon="help" label="Yardım ve Destek"/></div><img className="profile-banner" src="/images/flowly/flower-calla.webp" alt=""/><Link href="/giris" className="logout-link">Çıkış Yap</Link></section></ScreenShell>; }

function SettingsScreen() { const router = useRouter(); const [training, setTraining] = useState(true); const [suggestions, setSuggestions] = useState(true); const [saved, setSaved] = useState(false); return <ScreenShell className="settings-screen"><TopBar title="Profil ve Ayarlar" action={<button className="save-button" onClick={() => { setSaved(true); window.setTimeout(() => router.push("/profil"), 350); }}>{saved ? "Kaydedildi" : "Kaydet"}</button>}/><section><div className="edit-photo"><img src="/images/flowly/onboarding.webp" alt="Elif Yılmaz"/><button>Fotoğrafı<br/>Değiştir</button></div><div className="settings-list"><SettingRow icon="user" label="Ad Soyad" value="Elif Yılmaz"/><SettingRow icon="mail" label="E-posta" value="elif@yilmaz.com"/><SettingRow icon="phone" label="Telefon" value="+90 532 456 78 90"/><SettingRow icon="pin" label="İlçe" value="Kadıköy"/></div><h2>Tercihler</h2><PreferenceRow icon="bell" label="Antrenman hatırlatmaları" sub="Yaklaşan seanslar için bildirim al." value={training} onChange={setTraining} tone="moss"/><PreferenceRow icon="level" label="Yeni stüdyo önerileri" sub="Yakınındaki stüdyo ve etkinliklerden haberdar ol." value={suggestions} onChange={setSuggestions} tone="blue"/><h2>Hesap</h2><div className="settings-list"><SettingRow icon="lock" label="Şifreyi Değiştir"/><SettingRow icon="document" label="Gizlilik Ayarları"/><SettingRow icon="trash" label="Hesabı Sil"/></div></section></ScreenShell>; }
function PreferenceRow({ icon, label, sub, value, onChange, tone }: { icon: FlowlyIconName; label: string; sub: string; value: boolean; onChange: (value: boolean) => void; tone: string }) { return <label className="preference-row"><FlowlyIcon name={icon}/><p><strong>{label}</strong><span>{sub}</span></p><input className={`toggle ${tone}`} type="checkbox" checked={value} onChange={(event) => onChange(event.target.checked)}/></label>; }

function NotificationsScreen() { const flowly = useFlowly(); return <ScreenShell className="notifications-screen"><TopBar action={<button onClick={() => flowly.setNotificationsRead(true)}>{flowly.notificationsRead ? "Tümü okundu" : "Tümünü okundu işaretle"}</button>}/><section><h1>Bildirimler</h1><h2>Bugün</h2><NotificationRow icon="calendar" title="Rezervasyonun onaylandı" sub="Move Studio — 4 Ekim Cumartesi, 18:30" time="10:24" read={flowly.notificationsRead}/><NotificationRow icon="clock" title="Dersine 2 saat kaldı" sub="Move Studio — Reformer Pilates" time="16:30" read={flowly.notificationsRead}/><NotificationRow icon="user" title="Duygu K. yeni bir saat açtı" sub="Move Studio — Mat Pilates · Cumartesi, 11:00" time="12:14" read={flowly.notificationsRead}/><img className="notification-banner" src="/images/flowly/notification-flower.webp" alt=""/><h2>Bu Hafta</h2><NotificationRow icon="studio" title="Yeni bir stüdyo seni bekliyor" sub="The Balance — Kadıköy’de yeni dersler keşfet." time="2 Eki" read/></section></ScreenShell>; }
function NotificationRow({ icon, title, sub, time, read }: { icon: FlowlyIconName; title: string; sub: string; time: string; read: boolean }) { return <article className={`notification-row${read ? " is-read" : ""}`}><FlowlyIcon name={icon}/><div><strong>{!read && <i/>}{title}</strong><span>{sub}</span></div><time>{time}</time><FlowlyIcon name="arrow-right"/></article>; }

function TrainerDashboardScreen() { const flowly = useFlowly(); return <ScreenShell className="trainer-dashboard-screen" nav trainer><div className="status-row"><span>9:41</span><span>▮▮▮ ◉ ▰</span></div><header className="feed-header"><div><Brand/><p className="location-link"><FlowlyIcon name="pin"/>Eğitmen Paneli</p></div><Link href="/bildirimler"><FlowlyIcon name="bell" size={30}/><i/></Link></header><section><h1>Günaydın,<br/>Duygu.</h1><p>4 Ekim Cumartesi</p><div className="trainer-stats"><div><strong>{flowly.publishedClass ? 5 : 4}</strong><span>Ders</span></div><div><strong>18</strong><span>Katılımcı</span></div><div><strong>3</strong><span>Talep</span></div></div><div className="section-title-row"><h2>Bugünün akışı</h2><Link href="/egitmen-paneli/takvim">Tümünü Gör →</Link></div><div className="trainer-flow">{[["09:00","Reformer Pilates","5/6"],["12:30","Klinik Pilates","3/4"],["18:30","Reformer Pilates","6/6"]].map((item) => <Link href="/egitmen-paneli/takvim" key={item[0]}><strong>{item[0]}</strong><span>{item[1]}</span><em>{item[2]}</em><FlowlyIcon name="arrow-right"/></Link>)}</div><img className="trainer-banner" src={studios[0].image} alt=""/><div className="section-title-row"><h2>Bekleyen talepler</h2><Link href="/egitmen-paneli/talepler">Tümünü Gör →</Link></div><Link className="pending-preview" href="/egitmen-paneli/talepler/selin-aras"><img src="/images/flowly/member-selin.webp" alt=""/><div><strong>Zeynep A.</strong><span>Reformer Pilates · 7 Ekim Salı · 18:30</span></div><FlowlyIcon name="arrow-right"/></Link></section></ScreenShell>; }

function NewClassScreen() { const router = useRouter(); const flowly = useFlowly(); const [repeat, setRepeat] = useState(false); const [note, setNote] = useState(""); const [loading, setLoading] = useState(false); function publish() { setLoading(true); window.setTimeout(() => { flowly.setPublishedClass(true); router.push("/egitmen-paneli/takvim?published=1"); }, 500); } const rows: Array<[FlowlyIconName,string,string]> = [["pin","Stüdyo","Move Studio"],["mat","Ders türü","Reformer Pilates"],["calendar","Tarih","8 Ekim Perşembe"],["clock","Başlangıç","18:30"],["hourglass","Süre","50 dk"],["users","Kontenjan","6 kişi"],["level","Seviye","Orta Seviye"],["tag","Ücret","450 TL"]]; return <ScreenShell className="new-class-screen"><TopBar/><section><h1>Yeni Ders Saati</h1><p>Stüdyonda sunacağın yeni ders saatini<br/>oluştur ve yayınla.</p><div className="new-class-list">{rows.map(([icon,label,value]) => <button key={label}><FlowlyIcon name={icon}/><strong>{label}</strong><span>{value}</span><FlowlyIcon name="arrow-right"/></button>)}<label><FlowlyIcon name="repeat"/><strong>Tekrarlayan ders</strong><input type="checkbox" className="toggle" checked={repeat} onChange={(event) => setRepeat(event.target.checked)}/></label></div><label className="note-field"><span><FlowlyIcon name="document"/>Not <small>(isteğe bağlı)</small></span><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Dersle ilgili ek bilgi ekleyebilirsin..."/></label><PrimaryButton loading={loading} onClick={publish}>Dersi Yayınla</PrimaryButton></section></ScreenShell>; }

function RequestsScreen() { const flowly = useFlowly(); const [tab, setTab] = useState<"pending" | "approved" | "rejected">("pending"); const visible = requests.filter((request) => flowly.requestStates[request.id] === tab); return <ScreenShell className="requests-screen" nav trainer><header className="brand-action"><Brand/><FlowlyIcon name="search"/></header><section><h1>Rezervasyon<br/>Talepleri</h1><div className="tab-row request-tabs"><button className={tab === "pending" ? "is-active" : ""} onClick={() => setTab("pending")}>Bekleyen <b>{Object.values(flowly.requestStates).filter((state) => state === "pending").length}</b></button><button className={tab === "approved" ? "is-active" : ""} onClick={() => setTab("approved")}>Onaylanan</button><button className={tab === "rejected" ? "is-active" : ""} onClick={() => setTab("rejected")}>Reddedilen</button></div><div className="request-list">{visible.map((request) => <article key={request.id}><div className="request-person"><img src={request.image} alt=""/><div><strong>{request.name}</strong><span>{request.lesson}</span><span>{request.date} · {request.duration}</span><span><FlowlyIcon name="level"/>{request.level}</span></div><time>{request.age}</time></div>{tab === "pending" && <div className="request-actions"><PrimaryButton href={`/egitmen-paneli/talepler/${request.id}`} outline>İncele</PrimaryButton><button onClick={() => flowly.setRequestState(request.id, "approved")}>Onayla</button></div>}</article>)}</div>{!visible.length && <div className="empty-state"><FlowlyIcon name="users" size={42}/><h2>Bu bölümde talep yok.</h2></div>}</section></ScreenShell>; }

function RequestDetailScreen() { const router = useRouter(); const flowly = useFlowly(); const [note, setNote] = useState(""); const [busy, setBusy] = useState(false); function decide(state: "approved" | "rejected") { setBusy(true); window.setTimeout(() => { flowly.setRequestState("selin", state); router.push("/egitmen-paneli/talepler"); }, 450); } return <ScreenShell className="request-detail-screen"><TopBar title="Talep Detayı"/><section><div className="request-profile"><img src="/images/flowly/member-selin.webp" alt="Selin Aras"/><div><h1>Selin Aras</h1><StatusBadge tone="moss">Yeni Üye</StatusBadge></div></div><h2>8 Ekim, 18:30</h2><div className="request-detail-list"><SummaryRow icon="mat" label="" value="Reformer Pilates"/><SummaryRow icon="level" label="" value="Orta Seviye"/><SummaryRow icon="pin" label="" value="Move Studio"/><SummaryRow icon="clock" label="" value="50 dk"/></div><h3>Üye notu</h3><p>Bel hassasiyetim var; kontrollü çalışmayı tercih ediyorum.</p><h3>Geçmiş</h3><div className="history-row"><FlowlyIcon name="calendar"/><p><strong>6 tamamlanan ders</strong><span>Flowly’deki toplam ders sayısı</span></p><div><span>★</span><strong>4.8</strong><small>(32 değerlendirme)</small></div></div><label className="note-field"><span>Yanıt notu <small>(opsiyonel)</small></span><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Üyeye iletmek istediğiniz bir not yazın..."/></label><PrimaryButton loading={busy} onClick={() => decide("approved")}>Talebi Onayla</PrimaryButton><button className="text-button" onClick={() => decide("rejected")} disabled={busy}>Reddet</button></section></ScreenShell>; }

const calendarDays = Array.from({ length: 35 }, (_, index) => index < 3 ? 28 + index : index - 2);
function TrainerCalendarScreen() { const flowly = useFlowly(); return <ScreenShell className="trainer-calendar-screen" nav trainer><header className="brand-action"><Brand/><FlowlyIcon name="search"/></header><section><h1>Ders Takvimi</h1><div className="calendar-month"><button>‹</button><strong>Ekim 2026</strong><button>›</button></div><div className="calendar-weekdays">{["Pzt","Sal","Çar","Per","Cum","Cmt","Paz"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{calendarDays.map((day,index) => <button key={`${day}-${index}`} className={`${day === 8 ? "is-selected" : ""}${index < 3 || index === 34 ? " is-muted" : ""}`}>{day}{[3,6,7,8,9,10,13,15,16,20,23,24].includes(day) && <i className={day % 5 === 0 ? "blue" : "moss"}/>}</button>)}</div><div className="section-title-row"><h2>8 Ekim Perşembe</h2><Link href="/egitmen-paneli/yeni-ders" className="new-time"><i><FlowlyIcon name="plus"/></i>Yeni Saat</Link></div><div className="timeline">{[["09:00","Reformer Pilates","5 / 6 katılımcı",studios[0].image],["12:30","Klinik Pilates","3 / 4 katılımcı",studios[1].image],["18:30","Reformer Pilates","6 / 6 katılımcı",studios[0].image]].map((item,index) => <article key={item[0]} className={index === 2 ? "is-current" : ""}><time>{item[0]}</time><img src={item[3]} alt=""/><div><strong>{item[1]}</strong><span>{item[2]}</span><span><FlowlyIcon name="pin"/>Move Studio</span></div><FlowlyIcon name="arrow-right"/></article>)}{flowly.publishedClass && <p className="local-state-note">Yeni ders saati takvime eklendi.</p>}</div></section></ScreenShell>; }

export function FlowlyScreen({ screen }: { screen: FlowlyScreenId }) {
  const screens: Record<FlowlyScreenId, React.ReactNode> = {
    splash: <SplashScreen/>, onboarding: <OnboardingScreen/>, signup: <SignupScreen/>, login: <LoginScreen/>, reset: <ResetScreen/>, location: <LocationScreen/>, discover: <DiscoverScreen/>, map: <MapScreen/>, search: <SearchScreen/>, studio: <StudioScreen/>, instructor: <InstructorScreen/>, "class-select": <ClassSelectScreen/>, "booking-summary": <BookingSummaryScreen/>, success: <SuccessScreen/>, bookings: <BookingsScreen/>, "booking-detail": <BookingDetailScreen/>, favorites: <FavoritesScreen/>, reviews: <ReviewsScreen/>, "write-review": <WriteReviewScreen/>, profile: <ProfileScreen/>, settings: <SettingsScreen/>, notifications: <NotificationsScreen/>, "trainer-dashboard": <TrainerDashboardScreen/>, "new-class": <NewClassScreen/>, requests: <RequestsScreen/>, "request-detail": <RequestDetailScreen/>, "trainer-calendar": <TrainerCalendarScreen/>,
  };
  return screens[screen];
}
